### ISSUE TITLE
[feature-request] Can we add multiple intervals?

### ISSUE THREAD

**Issue by avatar-lavventura** [alleyway/add-tradingview-alerts-tool#105]
In config file we have:

```
# examples: 1s | 30s | 1m | 15m | 1h | 1D | 1M
  interval: 4h
```

Would it be possible to apply multiple intervals for the same signal?

For example:

```interval: 4h, 1D``` will apply alerts for `4h` and `1D`.

**Comment by ApopheniaPays** [comment]
You can set a custom column in the CSV and use tokens in the yml file. Can you use that to create a column for the interval for each alert and use {{interval}} in the "Interval" field in the yml?

**Comment by avatar-lavventura** [comment]
@ApopheniaPays In which file should i make changes? Should I make changes only on the `yml` file?

**Comment by mlake** [comment]
multiple intervals going into imminent 2.0 release
