### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by LarryEitel** [alleyway/add-tradingview-alerts-tool#107]
Please allow me to present a question here because someone involved with this project would likely know.

I would like to essentially fire an alert triggered by a mouse-click, ie, ctrl-alt-right-mouseclick for example.

This would fire a websocket message with relevant details, ie, price, symbol, etc.

Basically, I would like to fire special arbitrary commands via websocket directly from TV.

ANY thoughts would be most appreciated.

As a side point, the email confirmation was never sent when logging into https://alertzmanager.io/. I am very interested to beta the project.

Thank You

**Comment by mlake** [comment]
Email confirmation on alertzmanager.io should be working now.

As for your idea, you wouldn't be able to do that directly from tradingview, but definitely if you created a custom solution utilizing tradingview's charts for 3rd part devs
