### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xserrman2080** [alleyway/add-tradingview-alerts-tool#108]
hi, I get this error when I launch the script:

sergeyuzhakin@Sergeys-MBP tradingview-alerts-home % ./atat add-alerts
ℹ ATAT Version: 1.9.4 | Node Version: v16.13.1                        18:04:23
ℹ Current log level: 3 (you can specify '--loglevel 5' for maximum debugging)
ℹ Base delay: 1000 (you can specify '--delay 1000' (or env variable BASE_DELAY) to increase/decrease speed)
ℹ Using config file:  config.yml                                      18:04:23
ℹ Press Ctrl-C to stop this script                                    18:04:23

 ERROR  Cannot read properties of undefined (reading 'symbol')        18:04:23

  at addAlertsMain (node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:98:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at Command.<anonymous> (node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:77:13)

sergeyuzhakin@Sergeys-MBP tradingview-alerts-home % 
sergeyuzhakin@Sergeys-MBP tradingview-alerts-home %

**Comment by mlake** [comment]
I believe this has been addressed now
