### ISSUE TITLE
Modifying csv headers for Stocks

### ISSUE THREAD

**Issue by ricardodacosta** [alleyway/add-tradingview-alerts-tool#109]
Hey I was wondering if you can tell me which file I have to edit in order for the program to be okay with just symbol column on csv file. I want to see if I can use the tool for a list of stock alerts. Let me know if its possible
Thank you!

**Comment by mlake** [comment]
yes, you could use anything that tradingview supports in the symbol column of the .csv file.
you could leave quote and base empty if you don't need to do string replacement in the message for webhook calls
