### ISSUE TITLE
Not an issue, but may be helpfull to add to the install guide

### ISSUE THREAD

**Issue by sstrijak** [alleyway/add-tradingview-alerts-tool#110]
1. After installing nodes, also had to run "npm install --save-dev source-map-support"
2. After running "npx @alleyway/create-tradingview-alerts-home", also had to clone, create folder path and copy "dist" folder to "Q:\tradingview-alerts-home\node_modules\@alleyway\add-tradingview-alerts-tool" folder.

**Comment by mlake** [comment]
Thanks. Made some improvements based on this. Will need to test on windows better.
