### ISSUE TITLE
Feature Request - Ability to select a specific alert conditions when multiple with same name exist

### ISSUE THREAD

**Issue by Maacus** [alleyway/add-tradingview-alerts-tool#112]
If possible, it would be really beneficial to be able to select a specific alert condition when multiple of the same name exist.

For example, if the creator of the indicator has failed to distinguish by name the different plots of the alert, as such they are all named the name, therefore the alert tool is unable to select the correct one.

I've attached an example, if the user could enter something like 'plot[5]' to select the 5th one named 'plot' instead of the first.
![plot alert](https://user-images.githubusercontent.com/8881909/149616167-f1ca9ccc-7869-4edc-863c-43abb1641163.jpg)

**Comment by mlake** [comment]
This is a good idea and something that's been suggested before. I'll make a point to release this feature next week

**Comment by mlake** [comment]
hey - can you suggest an indicator that has these repeating options? I'm fishing around and not finding any at the moment..

**Comment by Maacus** [comment]
Hey, it's ['My MACD S/R](https://www.tradingview.com/script/02u68itU-My-MACD-S-R/#tc7893402)'.

Thanks

**Comment by mlake** [comment]
This is now possible using an zero-based index in version 2.3.1

in the example you posted, you should be able to use "Plot[4]" to select the fifth "Plot"
