### ISSUE TITLE
Bug since upgrade - Unable to find dropdown xpath target for primaryLeft/secondary

### ISSUE THREAD

**Issue by Maacus** [alleyway/add-tradingview-alerts-tool#117]
Since major version update to 2.1.2 from 1.9.4 I cannot create new alerts, have created a fresh install and also reverted to 1.9.4 and same problem.

Have tried different indicators also to rule them out, same problem.

Once it correctly selects the correct base & quote, it cannot find the indicator, with the error:
`Unable to find dropdown xpath target for primaryLeft/secondary. Make sure chart layout is SAVED with an indicator that contains/matches this: [indicator name]`

Is a Windows 11 machine running powershell.

Edit: Wanted to add that it opens up the 'Create Alert' windows and this point generates the error, however it doesn't appear to actually try and select the indicator. It just does nothing, and remains there without attempting to choose any indicator let alone the one it cannot find.

**Comment by mlake** [comment]
still having trouble here?

**Comment by mlake** [comment]
not getting any response here, so closing...
