### ISSUE TITLE
How can I disable *Play Sound* option?

### ISSUE THREAD

**Issue by avatar-lavventura** [alleyway/add-tradingview-alerts-tool#119]
Under *More Actions*, there is *Play Sound* option. By default its always enabled. Can we disable *Play Sound* option?

Example view in the alert menu:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/18537398/155892363-162e540d-1c91-4552-9d7c-b8e044e20e33.png">

-------------------------------------------------------------------

Can I do something as follows? :

```yaml
actions:
    playSound: false
```

**Comment by mlake** [comment]
TradingView saves some settings as default after you save one.

So just create a random alert without sound, save it. then delete it. When you create a new alert it should be disabled.

**Comment by avatar-lavventura** [comment]
@mlake Thanks
