### ISSUE TITLE
how to set expiration time in the alert???

### ISSUE THREAD

**Issue by saffins** [alleyway/add-tradingview-alerts-tool#12]
Hello sir

thanks for this awesome tool
here in the config.yml i m looking for a parameter through which we can set expiration time  with open ended checkbox
see screenshot below 
thanks again for sharing this tool

![image](https://user-images.githubusercontent.com/45685481/110114934-5c9c7780-7ddb-11eb-8eab-5ee69f329009.png)

**Comment by mlake** [comment]
haven't added that function yet, but may be coming soon.
In the meantime you could just create an alert once manually with that option checked and tradingview will remember that setting for you

**Comment by saffins** [comment]
Hello sir

this is great tool but still it manual as we need to run it every day or every hour
is there anything available like coding a indicator once its coded and added to chart it gives us alerts lifetime
no need to create alerts manually
anything like that available??
i tried to add alertcondition() in one of my fav indicator but even after adding that i need to add alerts manually
i want to make it automated permanent

**Comment by sitanjob** [comment]
great tool, but I need to check open-ended checkbox, how can I help develop it?
