### ISSUE TITLE
Installation of new version error

### ISSUE THREAD

**Issue by ocmich74** [alleyway/add-tradingview-alerts-tool#121]
![image](https://user-images.githubusercontent.com/18384322/156111071-ed408a8d-8fc3-4909-a730-408c529f94a1.png)

How do I resolve this?

**Comment by m4ybee** [comment]
This worked for me: 

2) You can reinstall/update this project by running the following:

   npx @alleyway/create-tradingview-alerts-home

tip. do it inside the existing tradingview-alerts-home directory.

**Comment by ocmich74** [comment]
I tried that, didn't work.   I'm more concerned with the empty folder that won't delete.  I have 3 of them now that won't delete from my computer.

**Comment by mlake** [comment]
hi there - what versions of windows/node/npm are you using?

**Comment by ocmich74** [comment]
I am on windows 10.. Not sure node/npm because i deleted them a week ago and haven't added them back.

**Comment by newquestions** [comment]
The installation is broken. I am using the latest version of Windows 10, and Node and NPM.

Above image explicitly shows the problem. The installation may have worked in the past ... but not any longer.

**Comment by mlake** [comment]
hi @newquestions 

I don't have a windows machine, but I have tested installation on a Win10 virtual machine with no problems.

The more specific information you can give me, the better I could try to reproduce and fix the problem (as well as research how you might be able to remove those folders...)

when you say "latest version of node"...do you mean version 16 or 18?

will work on this today...

**Comment by mlake** [comment]
also...

were you using windows "Command Prompt"? or was it "Powershell"?
<img width="447" alt="screencap" src="https://user-images.githubusercontent.com/764071/175517164-0ac1d831-b759-4aea-86f9-8412b8e0667d.PNG">

**Comment by mlake** [comment]
Should be solved. but will keep this issue open for now

#123

**Comment by ocmich74** [comment]
My issues are solved. I was able to remove all the empty folders and I was able to reinstall the tool with zero issues.  Thank you for fixing this!

**Comment by newquestions** [comment]
Can confirm the new update has worked correctly. Thank you Michael.

One thing you may want to include in the docs is this idea ...

Seems Powershell has default protection in place for unsigned packages downloaded via the internet.

As a result, I had to run this command, which offers a temporary bypass on the unsigned package:

powershell -executionpolicy ByPass -File .\atat.ps1 fetch-symbols binance -q usdt

Thanks again!

**Comment by mlake** [comment]
interesting . hadn't come across that before. will add to troubleshooting
