### ISSUE TITLE
how do you delete folder called '.    this wont delete!

### ISSUE THREAD

**Issue by ocmich74** [alleyway/add-tradingview-alerts-tool#123]
how do you delete folder called '.    this wont delete!

![image](https://user-images.githubusercontent.com/18384322/157385405-0200679b-38fe-4c5f-bff4-31ff02ff828d.png)

**Comment by ocmich74** [comment]
![image](https://user-images.githubusercontent.com/18384322/157385365-2699d239-86ff-4fbb-8168-d1c3b856f909.png)

**Comment by Zmizo** [comment]
did you manage to delete it  ? @ocmich74

**Comment by newquestions** [comment]
Yep ... this is a joke. Re-started my computer (Windows 10) in safe mode ... no ability to delete the folder.

Started in COMMAND PROMPT MODE ... still not able to delete the damn direction ...

WTF!  I have three of these directories on my hard drive now ... and I can't even delete them from the command prompt, before windows even loads. Just for the record ... the instructions as also BS. Missing module. You should check your installation routine. It is broken.

**Comment by mlake** [comment]
I was able recreate the problem and find a **solution to remove the folder.**..

Try something like the following in Windows PowerShell:
```

rm -Recurse -Force "\\?\C:\Users\IEUser\tradingview-alerts-home\'."

```

**Comment by mlake** [comment]
The offending code has been identified.

The latest home creation tool is much more robust and will install the latest ATAT tool when re-initializing

```
npx @alleyway/create-tradingview-alerts-home

```

**Comment by TZEG** [comment]
> Yep ... this is a joke. Re-started my computer (Windows 10) in safe mode ... no ability to delete the folder.
> 
> Started in COMMAND PROMPT MODE ... still not able to delete the damn direction ...
> 
> WTF! I have three of these directories on my hard drive now ... and I can't even delete them from the command prompt, before windows even loads. Just for the record ... the instructions as also BS. Missing module. You should check your installation routine. It is broken.


i found a solution which has worked and folders are delete 

here 
https://www.youtube.com/watch?v=KneoCmUgx6Q

**Comment by newquestions** [comment]
Thanks Michael and please allow me to apologize for being rude in my comment (which I have since deleted).

I was incredibly frustrated - but you have resolved the issue. Genius programmer. Thanks man ... I appreciate your hard work.

**Comment by mlake** [comment]
all is forgiven (apologies are rare these days!) - I get how it could be frustrating - I'd be annoyed too
