### ISSUE TITLE
Enhancement not an issue

### ISSUE THREAD

**Issue by adamhazeldene** [alleyway/add-tradingview-alerts-tool#128]
Hi, would it be possible to include a trigger/option in the config file to enable/disable the sounds?

I just used this fantastic script to create 300+ alerts, and then realised that the sound was set to enabled. I will delete them all and re-create.

Thanks

![image](https://user-images.githubusercontent.com/77219225/177221776-cd17b08c-8d9c-42a1-8f2b-50a1bd2bf44c.png)

**Comment by mlake** [comment]
done.

## Upgrade Instructions
From your ``tradingview-alerts-home`` directory, run the following:

```bash
npx @alleyway/create-tradingview-alerts-home
```

see here:

https://github.com/alleyway/add-tradingview-alerts-tool/blob/master/create-tradingview-alerts-home/src/init/config.init.yml
