### ISSUE TITLE
Some feedback after using the UI for a few days (enhancements)

### ISSUE THREAD

**Issue by ocundale** [alleyway/add-tradingview-alerts-tool#129]
Great job on creating this - I think it's super useful as TV offers very little functionality surrounding alerts. I thought i'd give some feedback to help out in it's evolution!

Issue: I only want to apply to a handful of names, but it's a nightmare to find them in the list each time - I end up using a hack of making them all priority and then sorting by priority.
Fix: Add column "favourites" with a simple boolean star, so you can sort by starred items.

Issue: I had 30+ different alerts, so ticking each alert to enable for each name took a lot of time!
Fix: Add a 'select all' and 'select none' check box on the symbol assignments list.

At the moment, I am creating like 5 different alerts for each indicator on each separate time frame. I think it would be really cool if it were possible to create a single alert and apply to multiple timeframes in one go.

Also, if you could display error information in the UI, so when a job fails, you can click the 'i' and see what happened, this would be extremely useful! I sometimes received an email, but not always, and struggled a bit in finding issues sometimes, so having that info in the UI would be better than an email imo.

And less important, but a nice addition would be having a {{timeframe}} macro that just used the timeframe in the alert, so you could add it to the text and it would come through.

**Comment by mlake** [comment]
Thanks for the feedback!

Yes - assigning alerts individually is a pain - you can do so en-masse with ConfigureScript - but yeah, the main priorities are now make the UI a bit more friendly. Would we have to spell favorite with a "u"??

Also - not sure I quite understand the {{timeframe}} macro - "it would come through"....where? in the tv alert message? the alert name? would it be different than {{interval}} from tradingview https://www.tradingview.com/support/solutions/43000531021-how-to-use-a-variable-value-in-alert/

thanks again for the interest!

**Comment by mlake** [comment]
hey there - made same updates that might interest you - especially assigning alert configs

**Comment by ocundale** [comment]
Ah nice one! I'll give it a try today :)
And sorry for slow reply - i was away, but yes I didn't realise i can just use the 'interval' macro from TV instead - i will try this!
And you don't need to put the 'u' in favourite, either spelling is fine, but I just happen to speak the UK english!
