### ISSUE TITLE
alert dialog box issue

### ISSUE THREAD

**Issue by jarrydbarrah** [alleyway/add-tradingview-alerts-tool#136]
Hi team, sorry to bug you but I'm a relatively regular user of this tool who has come across a new issue out of nowhere. It looks like the script isn't able to tell if the alerts dialog box is open or not, despite it clearly being open in the chromium tab.

![Screen Shot 2022-12-07 at 11 59 10 am](https://user-images.githubusercontent.com/23492997/206061751-f693c78a-fc24-40ef-accc-ac579840ba0e.png)

I've tried re-downloading the symbol files, refreshing the config file and playing with the delay (both up and down) but can't seem to get it firing as per normal. Thanks again for a great tool and let me know if you can assist.

**Comment by p3relman** [comment]
Hi @mlake, as already pointed out by @jarrydbarrah I can confirm the issue comes from a breaking change in the TradingView interface for the alerts. 

Now there are 2 different tabs instead of 1 as before:

![tv-alert-new-interface](https://user-images.githubusercontent.com/105297904/206467478-2f421579-05b1-4536-ad84-90abf3f39dae.png)

Thanks for checking :pray:

**Comment by ricardodacosta** [comment]
Will a fix be released for this issue?

**Comment by p3relman** [comment]
There are new releases only on beta: https://github.com/alleyway/add-tradingview-alerts-tool/tags

I presume they're working on this issue.

**Comment by ricardodacosta** [comment]
Never mind. I figured it out. "npm install @alleyway/add-tradingview-alerts-tool@2.3.3-beta.7
" and I can confirm the beta release fixes the issues with new tab in alert window. Thank you guys!

**Comment by c931812** [comment]
Tried 2.3.3-beta.7 up to 2.4.1-beta.2 and can't get it to work, I keep getting this error:

_Unable_ to find dropdown xpath target for primaryLeft/secondary. Make sure chart layout is SAVED with an indicator that contains/matches this: Test 

[https://i.imgur.com/3daUxGm.png](url)

The script load without any issue but when "create alert" box load it just doesn't select my indicator, everything match in my config file and it used to work without any issues before TV decided to update their alert box layout..

Here is what I'm trying to achieve:

[https://i.imgur.com/fRs7iYm.png](url)

**Comment by c931812** [comment]
Tried 2.3.3-beta.7 up to 2.4.1-beta.2 and can't get it to work, I keep getting this error:

_ERROR Unable to find dropdown xpath target for primaryLeft/secondary. Make sure chart layout is SAVED with an indicator that contains/matches this: Test_

![Error](https://i.imgur.com/dryzkha.png)

![After script load](https://i.imgur.com/3daUxGm.png)

The script load without any issue but when "create alert" box load it just doesn't select my indicator, everything match in my config file and it used to work perfectly last year before TV decided to update their alert box layout..

![Config file](https://i.imgur.com/krTDnko.png)

Here is what I'm trying to achieve:

![What I want](https://i.imgur.com/fRs7iYm.png)

It looks like the xpath of the dropdown menu is not correct and it doesn't matches the element the script is trying to target. Can someone advise please?

**Comment by ricardodacosta** [comment]
That happens to me too sometimes. What has worked for me is to save the tradingview chart layout on the first symbol of your .CSV list and also remove every other indicator/strategy from the chart nad lastly not be on pine editor. Try that!

**Comment by c931812** [comment]
> That happens to me too sometimes. What has worked for me is to save the tradingview chart layout on the first symbol of your .CSV list and also remove every other indicator/strategy from the chart nad lastly not be on pine editor. Try that!

I've done that before but no luck so far.
