### ISSUE TITLE
Issue with new version 2.4.0

### ISSUE THREAD

**Issue by ricardodacosta** [alleyway/add-tradingview-alerts-tool#137]
Wasn't happening with the Beta version 
ERROR  Waiting for selector .//button[@data-name='notifications'] failed: Waiting failed: 20000ms exceeded

**Comment by ricardodacosta** [comment]
However the new beta version seems to fix it. If anyone else has the same error just update by running
npm install @alleyway/add-tradingview-alerts-tool@2.4.1-beta.2

**Comment by cmartin81** [comment]
If you install it you can just call `node_modules/@alleyway/add-tradingview-alerts-tool/dist/cli.js`instead of./atat
