### ISSUE TITLE
Issue with install ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by adamhazeldene** [alleyway/add-tradingview-alerts-tool#138]
Hi, I have moved this tool from my home windows PC to a Linux VM running ubuntu, and having trouble getting it to run.
I am getting the below error ERR_MODULE_NOT_FOUND

I am running latest versions of Node & npm. I have installed the latest version of the tool also using the @latest command.

Linux isnt my forte, so this may be something I am overlooking - but have been through the issues trying to find if anyone else has had the same issue or not.
Not currently getting far :(
Thanks in advance for any assistance!

![image](https://user-images.githubusercontent.com/77219225/210911758-cda207f7-28db-4382-a4dd-a25225e26ac5.png)

![image](https://user-images.githubusercontent.com/77219225/210912010-f04742c8-c303-48e9-9fc6-1b1d6bcfb0af.png)

**Comment by adamhazeldene** [comment]
Found the error, remove NodeJS v19 and use v18.

**Comment by GogeiD** [comment]
Hi @adamhazeldene, what version exactly of Node are you using? I am on v18.12 and can't make it work... any other tips?

@mlake I already tried #121 and still have problems. I am using Windows 10 with npm 8.19.2, and it doesn't matter if I try cmd or Powershell. I have been using the v1.9.4 of the tool without issues, but it stopped working with the new TradingView layout for adding alerts. Any leads? I appreciate your help.
