### ISSUE TITLE
 ERROR  Waiting for selector .//span[@data-name='notify-on-app']//input failed: Waiting failed: 20000ms exceeded

### ISSUE THREAD

**Issue by port120** [alleyway/add-tradingview-alerts-tool#148]
this error message popped up for the first time today - worked yesterday.
am using the latest version. thanks

 ERROR  Waiting for selector .//span[@data-name='notify-on-app']//input failed: Waiting failed: 20000ms exceeded

**Comment by mlake** [comment]
hi there - should be fixed now
