### ISSUE TITLE
Trigger - once per bar close

### ISSUE THREAD

**Issue by jamidusu** [alleyway/add-tradingview-alerts-tool#155]
Hi there.

Recently, there was a layout change in the Trigger section of Trading View's alarm settings. So, they responded to that issue by updating quickly. I encountered a problem while using the new updated version.

In TradingView, the default value of Trigger is set to only once. I am using an alarm program by modifying the config.yml file to use this once per bar close.

However, this part is done so quickly and without delay that if you set 100 alarms, about 20 do not change to once per bar close, but the alarm is set only once. Additionally, if the trigger part does not change, there is an error in that the message part below it cannot be modified.

I assume this error is because the trigger is set too quickly, but there may be other causes. thank you :)

**Comment by mlake** [comment]
Hi there - yes, looks like there needed to be a delay in there.

just made a quick patch release ...try updating

From your ``tradingview-alerts-home`` directory, run the following:

```bash
npm install @alleyway/add-tradingview-alerts-tool@2.6.6
```

**Comment by jamidusu** [comment]
> Hi there - yes, looks like there needed to be a delay in there.
> 
> just made a quick patch release ...try updating
> 
> From your `tradingview-alerts-home` directory, run the following:
> 
> ```shell
> npm install @alleyway/add-tradingview-alerts-tool@2.6.6
> ```



> hi there.
> 
> Thx for quick update. I followed your advice and ran npm install @alleyway/add-tradingview-alerts-tool@2.6.6 and ran the program, but the symptoms are still the same.
> 
> npx @alleyway/create-tradingview-alerts-home@latest, which is not an update method but a completely new installation method.
> 
> Even if I install a new file with this and run it from that folder, the problem is not resolved and the symptoms are the same. What should I do?

hi there.

Thx for quick update. I followed your advice and ran npm install @alleyway/add-tradingview-alerts-tool@2.6.6 and ran the program, but the symptoms are still the same.

npx @alleyway/create-tradingview-alerts-home@latest, which is not an update method but a completely new installation method.

Even if I install a new file with this and run it from that folder, the problem is not resolved and the symptoms are the same. What should I do?

**Comment by nathanccmiller** [comment]
I am also experiencing this issue. I don't believe it is an issue with timing but rather recognition of the new formatting. The error message I get in my terminal is:
 ERROR  No fire rate 'option' available, but one was specified in alert configuration: Once Per Bar Close

**Comment by mlake** [comment]
fixed in 3.0.1
