### ISSUE TITLE
Error when adding option (aka Trigger in Tradingview)

### ISSUE THREAD

**Issue by nathanccmiller** [alleyway/add-tradingview-alerts-tool#158]
Trying to add the option Once Per Bar to the alerts. However, I am met with the following error message:
 ERROR  No fire rate 'option' available, but one was specified in alert configuration: Once Per Bar

Confirmed that I am running version 3.0.0. Likely an update that Tradingview made to the trigger section. It is no longer a dropdown menu.

<img width="455" alt="Screen Shot 2024-02-21 at 10 44 25 PM" src="https://github.com/alleyway/add-tradingview-alerts-tool/assets/69825206/f73a2fd7-bceb-42e9-b4df-84d6621de2c6">

<img width="565" alt="Screen Shot 2024-02-21 at 10 47 17 PM" src="https://github.com/alleyway/add-tradingview-alerts-tool/assets/69825206/2c417597-4ec6-4aea-b76b-12460fbbd1b7">

**Comment by mlake** [comment]
hi there, thanks for the report - should be fixed in 3.0.1
