### ISSUE TITLE
Binance.us modification

### ISSUE THREAD

**Issue by ricardodacosta** [alleyway/add-tradingview-alerts-tool#18]
Is there a quick fix I can do to get the coins listed at Binance.US as supposed to Binance.com?

**Comment by mlake** [comment]
unless I'm mistaken, tradingview doesn't support binanceUS

**Comment by ricardodacosta** [comment]
I have a bot running from TradingView's Strategy Alerts to Binance.US. No issues there. 

I tried changing line 24 within the fetch-binance-pairs.js file "https://api.binance.com/api/v3/exchangeInfo" to "https://api.binance.us/api/v3/exchangeInfo" but didn't help. I do know that's the only difference with their API ".com" & ".us"

**Comment by mlake** [comment]
Yes, that’s what I believe the change would be.

Just don’t know what you’d put in the trading view search box…obviously not “BINANCE:BTCUSD” but something like “BINANCE-US:BTCUSD”…except that “BINANCE-US” does not exist on TV’s platform..

**Comment by ricardodacosta** [comment]
I don't know if it started today but I do see BINANCEUS listed on TV's platform now. On 3Commas I have the alerts firing from Binance charts on pairs supported on Binance.US and orders do go through

**Comment by mlake** [comment]
Ok - so I just pushed the code to the git repository master branch.

In the checkout directory you should be able to do “git pull” to grab the latest.

npm fetch:binanceus btc

..as an example

Let me know it’s working and I could close this issue

**Comment by ricardodacosta** [comment]
I can confirm running npm run fetch:binanceus usdt created the .csv file for all USDT pairs listed on Binance.US
Thank you so much!!!
