### ISSUE TITLE
Constant timeouts

### ISSUE THREAD

**Issue by akefallonitis** [alleyway/add-tradingview-alerts-tool#19]
node version v14.16.0
npm version 6.14.11

Althought connect and at some point manages to get the first alerts it fails on the next

![image](https://user-images.githubusercontent.com/24274227/111373227-52645e00-86a4-11eb-8849-10c22554ec95.png)

**Comment by mlake** [comment]
what kind of internet connection do you have? I might add configuration options to adjust the delay, if you want to you could set environment variables for DELAY_SHORT, DELAY_MEDIUM, and DELAY_LONG ...the defaults are 300,500, and 1000

**Comment by akefallonitis** [comment]
Hey and thanks for the quick response. My internet connection kind of sucks should i increase them ? also i saw some parameters for timewait should i change them too ?

**Comment by akefallonitis** [comment]
also i noticed that it stacks on every second add alert - and alert has a little delay before shows up in tradingview but the script already trying to search and continue with the next pair

**Comment by a-kefallonitis** [comment]
managed to get it through adding manually sleep times in each irritation . Thanks

**Comment by mlake** [comment]
try "hiding" your indicators before running the script. you can still set strategy alerts on hidden indicators, but the chart will load much faster

**Comment by mlake** [comment]
Updated a lot in the script - try the latest version, should resolve your issues
