### ISSUE TITLE
Bittrex & Coinbase Exchange would be great

### ISSUE THREAD

**Issue by ricardodacosta** [alleyway/add-tradingview-alerts-tool#20]
Hey this tool is amazing!!! I have been doing this manually with over 200 alerts for a long time! 
Not sure how troublesome this might be for you but adding the exchanges Bittrex and Coinbase would be awesome but no rush!

Alternatively I wonder if there could be a possibility to add the option for the trader to fill up a .csv file with symbols and exchange/broker information and allow the tool to simply add the alerts based on such file without the need to connect/download symbols from a particular broker/exchange. This would allow those interested in Forex and/or Stocks to take advantage of the tool as well

Will be donating some ETH at the end of the week _/\_

**Comment by mlake** [comment]
![image](https://user-images.githubusercontent.com/764071/111534059-d6334e80-8767-11eb-817d-bd61d379b7c9.png)

Done!

**Comment by mlake** [comment]
fyi, there's no reason you couldn't create a .csv file with stock tickers in the "symbol" column. you're free to leave the quote and base columns empty
