### ISSUE TITLE
Can't add more than two alarm 

### ISSUE THREAD

**Issue by DungPT10** [alleyway/add-tradingview-alerts-tool#24]
Hi Sir,
Now it can't add more than two alarm.
with first alarm ETHBTC it's ok,
with second alarm LTCBTC it's not ok, it request upgrade to Premium account to get more alarm.

![image](https://user-images.githubusercontent.com/69800731/111691093-81bfca00-8860-11eb-84b7-450ab9a609d6.png)

And this is error !
![image](https://user-images.githubusercontent.com/69800731/111689267-62c03880-885e-11eb-8e58-0c9a01789520.png)

**Comment by mlake** [comment]
sounds like maybe you need to update your tradingview account

I just pushed some changes that should help fix the timing of some actions
