### ISSUE TITLE
Is it possible to trigger automated backtest results?

### ISSUE THREAD

**Issue by nmenescardi** [alleyway/add-tradingview-alerts-tool#29]
Hi. Backtest a strategy with several combination of parameters is a pain in TV. It'd be great to have a way to set a combination of parameters and get metrics for each run. Is it something you're planning to add?

**Comment by mlake** [comment]
I haven’t done any backtest testing yet…sounds like it would be a useful feature though. Will consider

**Comment by marcfon** [comment]
This would be a great feature to have for sure!
