### ISSUE TITLE
npm run fetch:binance:btc does not work

### ISSUE THREAD

**Issue by lfr79** [alleyway/add-tradingview-alerts-tool#3]
Hello, it seems that fetch:binance:btc does not work as it runs tsc && **env** QUOTE_ASSET=BTC node lib/fetch-binance-pairs.js > binance_btc_pairs.csv instead of tsc && **cross-env** as in fetch usdt pairs 

"env" is not recognized as an internal program
[2020-11-13T19_01_37_316Z-debug.log](https://github.com/alleyway/add-tradingview-alerts-tool/files/5538990/2020-11-13T19_01_37_316Z-debug.log)
.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alleyway/add-tradingview-alerts-tool@1.1.0 fetch:binance:btc: `tsc && env QUOTE_ASSET=BTC node lib/fetch-binance-pairs.js > binance_btc_pairs.csv`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @alleyway/add-tradingview-alerts-tool@1.1.0 fetch:binance:btc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I'm not a programmer myself so please forgive me if I'm doing something wrong. I was trying to run the script manually but was not really successful

**Comment by mlake** [comment]
You are right in making that modification - I've updated the code but haven't tested it since I don't have a windows machine.
should work though.

let me know if it does not

**Comment by lfr79** [comment]
I confirm that everything is fine with fetch:binance:btc now. Thanks!
