### ISSUE TITLE
Error when choose option

### ISSUE THREAD

**Issue by tresmastres** [alleyway/add-tradingview-alerts-tool#30]
Hello

I'm using this tool since V 1.0.0 and works fine, but when I update to last version the routine stucks when have to choose options
Only once
Only once per bar close, etc....

and give this error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alleyway/add-tradingview-alerts-tool@1.6.9 add-alerts: `npx tsc && npx cross-env node -r source-map-support/register dist/add-alerts.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @alleyway/add-tradingview-alerts-tool@1.6.9 add-alerts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any help?
Thanks in advance.

**Comment by ytfuzzy** [comment]
Hey @tresmastres , Did you manage to find a fix? 
Turns out that im having the same exact situation.

**Comment by tresmastres** [comment]
last version is running well for me
