### ISSUE TITLE
Is it possible to take snapshots and copy the URL?

### ISSUE THREAD

**Issue by thanksonlinebusiness** [alleyway/add-tradingview-alerts-tool#36]
Hi, 

I love your current script. I am not always programming but it was so easy to use and I was wondering if it would be possible to add the functionality to take screenshots (Alt+S) and then copy the code similar to what they try to do here: 

https://stackoverflow.com/questions/58144204/python-selenium-getting-trading-view-url-of-the-snapshot

Thank you very much!

**Comment by mlake** [comment]
for what purpose?
