### ISSUE TITLE
It doesn't download/install the correct chromium version as it seems

### ISSUE THREAD

**Issue by dominikheiss** [alleyway/add-tradingview-alerts-tool#37]
Hey, first thanks for that great tool!
My machine: win10 1909, v14 or v15 node js.

![image](https://user-images.githubusercontent.com/70059992/114273768-b831d480-9a1b-11eb-8d8c-bff903116ef8.png)

Or did I do something wrong?

Second question: is it possible to get a Binance-Futures (USDT) list with your magic tool? :)

Regards

**Comment by mlake** [comment]
Hi there - there've been a few changes to the installation procedure - perhaps you could try installing again from scratch? (follow the new instructions on the github README

cheers,
MIchael

**Comment by mlake** [comment]
try the new version which should resolve much of your problems and also has binance futures
