### ISSUE TITLE
Issue to get exchange data .csv

### ISSUE THREAD

**Issue by Neetoo** [alleyway/add-tradingview-alerts-tool#38]
Hello,

I have this error when I want to have the .csv file... Could you help me please ?

`$ npm run fetch:binance usdt

> @alleyway/add-tradingview-alerts-tool@1.6.10 fetch:binance C:\Users\Neetoo\Desktop\Trading\add-tradingview-alerts-tool-master\test\add-tradingview-alerts-tool
> npx tsc && npx cross-env EXCHANGE=BINANCE node --es-module-specifier-resolution=node -r source-map-support/register dist/fetch-pairs.js "usdt"

node: --es-module-specifier-resolution requires --experimental-modules be enabled
npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! @alleyway/add-tradingview-alerts-tool@1.6.10 fetch:binance: `npx tsc && npx cross-env EXCHANGE=BINANCE node --es-module-specifier-resolution=node -r source-map-support/register dist/fetch-pairs.js "usdt"`
npm ERR! Exit status 9
npm ERR!
npm ERR! Failed at the @alleyway/add-tradingview-alerts-tool@1.6.10 fetch:binance script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Neetoo\AppData\Roaming\npm-cache\_logs\2021-04-10T15_52_26_678Z-debug.log
`

**Comment by mlake** [comment]
Hi there - which version of node are you using? Seems like maybe you have an old one..

**Comment by Neetoo** [comment]
I have the v12.16.3

**Comment by Neetoo** [comment]
Problem solved, I just upgraded my version, really thanks.
