### ISSUE TITLE
Errors when running the script

### ISSUE THREAD

**Issue by liyoungc** [alleyway/add-tradingview-alerts-tool#40]
Hi:

Thanks for your works, saving lots of time!
I helped two friends setting up this tool, but they encountered different problems:
The first one, it can't find the expected Chromium (even after npm i chromium)
The second one, it can't launch the browser process. Went to puppeteer's troubleshooting page but can't find much help. What can I do for them? Thanks!

<img width="948" alt="Error-1 1" src="https://user-images.githubusercontent.com/20261800/114323991-66dc2f00-9b5a-11eb-9a14-5d91aa2e3e41.png">
<img width="950" alt="Error-1 2" src="https://user-images.githubusercontent.com/20261800/114323993-68a5f280-9b5a-11eb-91b8-4010142737f7.png">
![Error-2 1](https://user-images.githubusercontent.com/20261800/114324126-10232500-9b5b-11eb-87ef-d08b00c3a2df.png)

**Comment by liyoungc** [comment]
![Error-2 1](https://user-images.githubusercontent.com/20261800/114324135-1dd8aa80-9b5b-11eb-90ff-31f4103a2c10.png)

**Comment by mlake** [comment]
Hi there - have you tried lately? I hit this issue once and since I updated puppeteer in the project it seems to work fine to find the browser..

**Comment by mlake** [comment]
Update the tool by running the following:

```
npx @alleyway/create-tradingview-alerts-home
```
