### ISSUE TITLE
Alert creation -  order of operation

### ISSUE THREAD

**Issue by berryp1224** [alleyway/add-tradingview-alerts-tool#42]
Hello - I am creating an alert that uses Primary Left and Primary Right.

The issue is the Primary Right does not show up until the Secondary option is changed to Crossing Down.  

Is there a way to change the order of operation to change the secondary option to Crossing Down before entering the Primary Options?

**Comment by mlake** [comment]
Interesting…is the indicator available for me to reproduce? Which exact conditions are you using?

Thanks,
Michael

**Comment by berryp1224** [comment]
The script below is by LazyBear.  The alert condition at the bottom was added.  You can add this as a custom script to test it.



//
// @author LazyBear
//
// If you use this code in its original/modified form, do drop me a note. 
//
study(title="WaveTrend with Crosses", shorttitle="WT_CROSS_LB")
n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)

wt1 = tci
wt2 = sma(wt1,4)

newColor = wt2 - wt1 > 0 ? red : green

plot(0, title="Zero Line")
plot(obLevel1, title="Overbought Lv.1")
plot(obLevel2, title="Overbought Lv.2")
plot(osLevel1, title="Oversold Lv.1")
plot(osLevel2, title="Oversold Lv.2")

plot(wt1, title="WT Bull Line")
plot(wt2, title="WT Bear Line")
plot(wt1-wt2, color = newColor, style=area, transp=80, title="Histo")
plot(cross(wt1, wt2) ? wt2 : na, color = black , style = circles, linewidth = 3, title="WT Crossing Outline")
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red : lime) , style = circles, linewidth = 2, title="WT Crossing Dots")

// Set Alerts for Bull/Bear Cross
wtCross = cross(wt1, wt2)
alertcondition(wtCross, title="Wave Trend Crossing", message="Wave Trend Crossing")

**Comment by berryp1224** [comment]
The conditions I am using are:  
Primary Left:  WT_CROSS_LB
Primary Right:  WT Bull Line
Secondary:  Crossing Down
Tertiary Left:  WT_CROSS_LB
Tertisary Right:  Oversold Lv.2

**Comment by mlake** [comment]
Thanks for providing that info - I was able to successfully reproduce and release a new version which should handle this scenario.

Could you give it a shot? 
updated some dependencies, so you might need to do an "npm install"
if it works, we can close this issue

**Comment by berryp1224** [comment]
Hello - This is fixed now.  Confirmed working.  Thank you for the quick response!

**Comment by berryp1224** [comment]
Hello Michael - I had a question about pulling the csv files down (Binance
in this case) for USDT and BTC pairs.  Is there a way to pull list by
market cap?  For example I would love to pull the USDT pairs for the TOP
100 or 200 coins only by Market Cap.

Just curious if this is possible.  Currently I have to go through the full
list manually and remove the coins that have low marketcaps.

Thank you

Paul B.
