### ISSUE TITLE
Support for Strategies

### ISSUE THREAD

**Issue by FTomasz** [alleyway/add-tradingview-alerts-tool#43]
I've noticed that when I attempt to create an alert using a strategy rather than it doesn't want to work, I've attempted to look into the code, I'll be honest I would have no idea what to change, I figure I just need to disable Secondary and tertiary elements for it to work, as the strategy already establishes under what criteria it would need to send an alert, please could someone assist me, I'll make it worth your while! I promise!

**Comment by mlake** [comment]
Hi - did you grab the latest? There was an issue pressing the “continue” button on strategy alerts that should be fixed now…

You might want to keep your configuration file and follow the install instructions again..

Michael

**Comment by FTomasz** [comment]
Alrighty cheers, what should I put for Secondary and Tertiary, just leave them blank?

**Comment by FTomasz** [comment]
I've reset and reinstalled from scratch, same issue.

**Comment by mlake** [comment]
could you post your config? (obscure any bot ids if you have them)

Any chance this indicator is public so I can try to reproduce?

**Comment by mlake** [comment]
I think maybe you were making a custom pine script for which there was indeed a problem.

Just released 1.8.5 which should address your issue. closing for now..
