### ISSUE TITLE
issue with wrong secondary indicator being selected

### ISSUE THREAD

**Issue by cejkyle** [alleyway/add-tradingview-alerts-tool#47]
Love the script, thanks so much.
I am using it with Market Cipher.
The issue is that the condition is selected correctly but the secondary which is the actual indicator selects the first item in the drop down which is blue wave cross up (green dot) rather than the third option which is just Green Dot and the one I need.
How can i adjust so the drop down select the third option?
![Screen Shot 2021-05-06 at 10 48 49 pm](https://user-images.githubusercontent.com/47543038/117300789-42574680-aebd-11eb-8f5a-c8e7a5b92cab.png)

**Comment by mlake** [comment]
Ah looks like it’s matching the text since it just needs to include it…

Will push an update soon to allow regular expression matching

**Comment by mlake** [comment]
try doing the following in terminal from your tradingview-alerts-home directory:

```
tradingview-alerts-home $ npm install @alleyway/add-tradingview-alerts-tool@1.8.0

```

Then in your config file, specify the following:

```yaml
alert:
  condition:
    primaryLeft: /^Green Dot$/
```

**Comment by cejkyle** [comment]
Hi Michael.
Legend. Good luck with regex. Im a cloud infra developer but never managed
to get my head round regex.
I've added my self to the beta wait list
such a great product you have here you should deffo keep building it.
impressed by how easy it was to setup and worked reliably

One other question. is there any way you can think of to "chain" alerts so
i get notified when two alerts become true in a particular time frame?

love your work.
Thanks for the fast response. please let me know when done.
cheers

**Comment by cejkyle** [comment]
Will do, great suggestion.

**Comment by cejkyle** [comment]
Sory for slow response, been away for 2 weeks in a camper van and off the
grid.anyway got back and tried your suggestion and it worked great. thanks
so much!

**Comment by mlake** [comment]
😉
