### ISSUE TITLE
Error After recent update

### ISSUE THREAD

**Issue by thanksonlinebusiness** [alleyway/add-tradingview-alerts-tool#48]
I could use the tool before. However I can't manage to upgrade to new version.
 And I also get crashing browser on the version that used to work for me

```
Error: Command failed: cd /Users/.../AUTO Alerts creation/tradingview-alerts-home && npm install
    at checkExecSyncError (node:child_process:690:11)
    at execSync (node:child_process:727:15)
    at initializeMain (file:///Users/.../.npm/_npx/5455a11893b177f3/node_modules/@alleyway/create-tradingview-alerts-home/dist/index.js:76:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7570,
  stdout: null,
  stderr: null
}
```

**Comment by mlake** [comment]
What operating system?
Which version of node? 
maybe it’s the spaces in the file name… I just pushed an update which would handle it. Can you try the installation again please?

**Comment by mlake** [comment]
Hi there, I was able to recreate this problem on a windows machine...please run the following to update your project:

```
npx @alleyway/create-tradingview-alerts-home@latest
```
