### ISSUE TITLE
clash using Any alert() function call

### ISSUE THREAD

**Issue by jairocpv** [alleyway/add-tradingview-alerts-tool#49]
hi, the script clash when try to create alerts in a script tha uses the any alert() function call:

this is the call in my pine script:

if (validLong and _zignaly)
    alert(message=msgbuy, freq=alert.freq_once_per_bar_close)

![Captura de Tela (92)](https://user-images.githubusercontent.com/69261322/117523499-1a381800-af8f-11eb-9966-aa661a2dbe92.png)

**Comment by jairocpv** [comment]
PS C:\Windows\system32\add-tradingview-alerts-tool> npx atat --delay 550 --loglevel 5 add-alerts ZIG_API_RVS.cfg        i ATAT Version: 1.8.0 | Node Version: v14.16.0                                                                10:15:12
i Current log level: 5 (you can specify '--loglevel 5' for maximum debugging)                                 10:15:12
i Base delay: 550 (you can specify '--delay 1000' (or env variable BASE_DELAY) to increase/decrease speed)    10:15:12
i Using config file:  ZIG_API_RVS.cfg                                                                         10:15:12
i Press Ctrl-C to stop this script                                                                            10:15:12
» ...waiting 2750ms = 5 x 550  let page load and see if access is denied                                      10:15:14
» ...waiting 1650ms = 3 x 550  wait a little longer for page to load                                          10:15:18
» set interval: 15m                                                                                           10:15:19
» ...waiting 275ms = 0.5 x 550  after pressing interval shortcut key                                          10:15:19
» ...waiting 1650ms = 3 x 550  after changing the interval                                                    10:15:19
i Adding symbol: BINANCE:BTCUSDT  ( BTC priced in USDT )                                                      10:15:21
» ...waiting 1100ms = 2 x 550  let things settle from processing last alert                                   10:15:21
» ...selector: //div[@id="header-toolbar-symbol-search"]                                                      10:15:22
» ...waiting 550ms = 1 x 550                                                                                  10:15:23
» ...selector: //input[@data-role='search']                                                                   10:15:23
» ...waiting 1100ms = 2 x 550  after navigating to ticker                                                     10:15:23
» addAlert()...pressing shortcut key                                                                          10:15:25
» ...waiting 550ms = 1 x 550  after clicking shortcut for new alert dialog                                    10:15:25
» Processing primaryLeft: API                                                                                 10:15:25
» ...waiting 385ms = 0.7 x 550                                                                                10:15:25
» Searching potential dropdown xpath of primaryLeft                                                           10:15:26
» ...selector: //div[contains(@class, 'tv-alert-dialog__group-item--left ')]/span[@class='tv-control-select__wrap tv-dropdown-behavior tv-control-select--size_small']/span[@class='tv-control-select__control tv-dropdown-behavior__button']
» Found dropdown! Clicking element of primaryLeft                                                             10:15:26
» ...waiting 275ms = 0.5 x 550  let dropdown populate                                                         10:15:26
» searching menu for API                                                                                      10:15:26
» Found! Clicking API-RVS (5, 100, 96, 50, 14, 0.5, 1)                                                        10:15:26
» ...waiting 275ms = 0.5 x 550  let dropdown populate                                                         10:15:26
» Processing primaryRight: null                                                                               10:15:26
» ...waiting 385ms = 0.7 x 550                                                                                10:15:26
» Processing secondary: null                                                                                  10:15:27
» ...waiting 385ms = 0.7 x 550                                                                                10:15:27
» Processing tertiaryLeft: null                                                                               10:15:27
» ...waiting 385ms = 0.7 x 550                                                                                10:15:27
» Processing tertiaryRight: null                                                                              10:15:28
» ...waiting 385ms = 0.7 x 550                                                                                10:15:28
» Processing quaternaryLeft: undefined                                                                        10:15:28
» ...waiting 385ms = 0.7 x 550                                                                                10:15:28
» Searching potential dropdown xpath of quaternaryLeft                                                        10:15:28
» ...selector: (//div[contains(@class, 'tv-alert-dialog__group-item--left ') and contains(@class, 'js-second-operand-select-wrap__')]/span[@class='tv-control-select__wrap tv-dropdown-behavior tv-control-select--size_small' and 1]/span[@class='tv-control-select__control tv-dropdown-behavior__button'])[2]
» Timed out. Maybe it's not a dropdown. Search for 'input' xpath query                                        10:15:31
» ...selector: (//div[contains(@class, 'tv-alert-dialog__group-item--left ')]/div[contains(@class, 'js-number-input')]/input)[2]

 ERROR  waiting for XPath (//div[contains(@class, 'tv-alert-dialog__group-item--left ')]/div[contains(@class, 'js-number-input')]/input)[2] failed: timeout 3000ms exceeded

  at new WaitTask (C:\Windows\System32\add-tradingview-alerts-tool\node_modules\puppeteer\src\common\DOMWorld.ts:780:28)  at DOMWorld.waitForXPath (C:\Windows\System32\add-tradingview-alerts-tool\node_modules\puppeteer\src\common\DOMWorld.ts:675:22)
  at Frame.waitForXPath (C:\Windows\System32\add-tradingview-alerts-tool\node_modules\puppeteer\src\common\FrameManager.ts:1193:47)
  at Page.waitForXPath (C:\Windows\System32\add-tradingview-alerts-tool\node_modules\puppeteer\src\common\Page.ts:2111:29)
  at fetchFirstXPath (/C:/Windows/System32/add-tradingview-alerts-tool/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:15:20)
  at performActualEntry (/C:/Windows/System32/add-tradingview-alerts-tool/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:208:50)
  at configureSingleAlertSettings (/C:/Windows/System32/add-tradingview-alerts-tool/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:240:5)
  at addAlert (/C:/Windows/System32/add-tradingview-alerts-tool/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:331:5)
  at addAlertsMain (/C:/Windows/System32/add-tradingview-alerts-tool/node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:172:9)
  at Command.<anonymous> (/C:/Windows/System32/add-tradingview-alerts-tool/node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:67:13)

PS C:\Windows\system32\add-tradingview-alerts-tool>

**Comment by jairocpv** [comment]
i reinstalled the previous version 1.6.9 and it works now

**Comment by mlake** [comment]
This has been addressed in the 1.8.5 release. closing for now
