### ISSUE TITLE
feature to choose timeframe 

### ISSUE THREAD

**Issue by imerkle** [alleyway/add-tradingview-alerts-tool#5]
it would be helpful to also select timeframe

**Comment by mlake** [comment]
Hi - could you elaborate? what time frame? you mean time until alert expiration?

**Comment by mlake** [comment]
I made some modifications to your patch..
- instead of setting the interval before adding each pair, I just set it at the beginning
- changed the interval to be specified under the tradingview parent in the config
- interval format now matches what people see in tradingview 1s, 1m, 1H, 1D, etc
