### ISSUE TITLE
error running npx atat add-alerts

### ISSUE THREAD

**Issue by G1500** [alleyway/add-tradingview-alerts-tool#50]
i get an error when running npx atat add-alerts

terminal says:

 ERROR  All collection items must start at the same column            01:09:44

  at Collection.parse (node_modules/yaml/dist/parse-cst.js:331:24)
  at node_modules/yaml/dist/parse-cst.js:1605:29
  at CollectionItem.parse (node_modules/yaml/dist/parse-cst.js:92:19)
  at node_modules/yaml/dist/parse-cst.js:1586:25
  at Collection.parse (node_modules/yaml/dist/parse-cst.js:350:20)
  at node_modules/yaml/dist/parse-cst.js:1605:29
  at Document.parseContents (node_modules/yaml/dist/parse-cst.js:622:26)
  at Document.parse (node_modules/yaml/dist/parse-cst.js:685:19)
  at Object.parse (node_modules/yaml/dist/parse-cst.js:1729:18)
  at parseDocument (node_modules/yaml/dist/index.js:43:24)

Please let me know the solution.  If i can get this to  work, it will be incredible.
 Thanks!

**Comment by mlake** [comment]
Sounds like your config file is formatted incorrectly … I’d look at the example and make sure it’s indented correctly

**Comment by G1500** [comment]
how do i check? i copied the example to my BBEdit and tabbed between the 2 documents and it looks to be the same (except the necessary info i needed change).  Format wise its the same tho.  also i made sure to only copy and replace the necessary info.

**Comment by mlake** [comment]
which version of the tool you using? I’d start with the supplied config and make sure it launches…
Otherwise you could post your config and I could have a look

**Comment by G1500** [comment]
i reinstalled the tool again (by running npx @alleyway/create-tradingview-alerts-home ) by default its giving me version 1.1.0

**Comment by G1500** [comment]
im running:  ATAT Version: 1.8.0 | Node Version: v16.1.0  when i run the supplied config i get the same error

**Comment by G1500** [comment]
I Figured it out... i had some names in the wrong fields.  Thanks for your assistance!
