### ISSUE TITLE
 [ERROR]  Cannot read property 'toLowerCase' of undefined                                                                                                                                           14:21:54

### ISSUE THREAD

**Issue by angledarknet** [alleyway/add-tradingview-alerts-tool#52]
![image](https://user-images.githubusercontent.com/52553192/117563755-309abc80-b0d2-11eb-811e-24b8675f12c0.png)

**Comment by mlake** [comment]
Hi Pablo - looks like your csv format might be messed up

**Comment by angledarknet** [comment]
> Hi Pablo - looks like your csv format might be messed up

Thank you,
I forgot to put "symbol, quote, base, name".
Hahhahahha
