### ISSUE TITLE
Invalid CSV file format

### ISSUE THREAD

**Issue by j0hye** [alleyway/add-tradingview-alerts-tool#53]
Getting "Invalid CSV file format" error after fetching pairs since latest update.

![image](https://user-images.githubusercontent.com/83937665/117606018-4dc69e00-b159-11eb-9770-a0e0f64acaa3.png)

**Comment by mlake** [comment]
oops, my bad..just released a hotfix! Run the following in that directory to update

```
npm install @alleyway/add-tradingview-alerts-tool@1.8.2
```
