### ISSUE TITLE
Unable to upgrade version

### ISSUE THREAD

**Issue by ramnite** [alleyway/add-tradingview-alerts-tool#54]
I have been using ATAT for some time.

Yesterday ATAT stopped working so I decided to upgrade. 

After installing node 14.16 and running `npx @alleyway/create-tradingview-alerts-home` I get the following error: `npm ERR! Cannot read property 'spec' of undefined`

![Screen Shot 2021-05-10 at 10 33 43](https://user-images.githubusercontent.com/80322035/117630760-ce969180-b17b-11eb-9d87-bc11a62b95c8.png)

**Comment by mlake** [comment]
Hi - thanks for reaching out...

having difficulty replicating this error.

is it possible you have an older version of npm installed?
```
npm --version
```

also, which OS are you using?

**Comment by ramnite** [comment]
Thanks for the fast response.

```
sh-3.2# npm --version
7.12.0
```

I am using macOS BigSur 11.3

**Comment by ramnite** [comment]
I have updated node using:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

and now I can see additional prompts. Give me a minute, I will see if the issue is solved and report back.

**Comment by ramnite** [comment]
It seems it was a problem with the node version.

After running the commands above, I have been able to create the "tradingview-alerts-home" directory.

I am able to fetch pairs. However, when I run add-alerts, I get `ERROR  Invalid csv file format`.

As recommended on https://github.com/alleyway/add-tradingview-alerts-tool/issues/53, I try to run `npm install @alleyway/add-tradingview-alerts-tool@1.8.2` but I get the following errors.

![Screen Shot 2021-05-10 at 11 25 45](https://user-images.githubusercontent.com/80322035/117637831-7c0ca380-b182-11eb-8d30-58f6eedbde57.png)

**Comment by ramnite** [comment]
Here they are.

[pairs_excluded.csv](https://github.com/alleyway/add-tradingview-alerts-tool/files/6451077/pairs_excluded.csv)
[pairs_included.csv](https://github.com/alleyway/add-tradingview-alerts-tool/files/6451078/pairs_included.csv)

**Comment by ramnite** [comment]
That was it.

Now I am getting errors during the alert creation process of the first alert, but I think that's related to my config.yml. Maybe the config.yml format has changed during the last version/s. That's a different topic/issue. I will work on it now to see if I can fix it on my own.

Thank you very much. I am closing this ticket now.
