### ISSUE TITLE
./atat MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by akefallonitis** [alleyway/add-tradingview-alerts-tool#57]
Hi 

I have downloaded the latest package 1.8.5 (i run an older version without a problem) and i am trying to run it following your instructions but i run on an error:

![image](https://user-images.githubusercontent.com/24274227/118236298-91454300-b49e-11eb-9a7d-cbf9298aef91.png)

Can you please assist ?

**Comment by mlake** [comment]
Hi there...try following the installation instructions from an entirely new directory. (you can copy your existing config there afterwards)

The installation process is quite different nowadays..

**Comment by akefallonitis** [comment]
Hi and thanks for your prompt response.

So i only have to do run these steps ? Or am i missing something ?

# make sure you're running at least node version 14.15.0
node -v 

# create your tradingview-alerts-home directory and/or upgrade version
npx @alleyway/create-tradingview-alerts-home

# Follow prompts to initialize your tradingview-alerts-home

**Comment by mlake** [comment]
yes...you shouldn't really need to download a zip file or unpack anything yourself (which does make the "releases" webpage confusing I guess)

**Comment by akefallonitis** [comment]
Mmm i created a new folder in the desktop and run npx @alleyway/create-tradingview-alerts-home but same error

Node version v14.16.0 Npm version 7.13.0

**Comment by akefallonitis** [comment]
![image](https://user-images.githubusercontent.com/24274227/118239199-20a02580-b4a2-11eb-87b0-3d15721d9864.png)

**Comment by mlake** [comment]
try running the following in that directory:

```
npm install
.\atat --version
```

**Comment by mlake** [comment]
also, it wouldn't hurt to run the following:

```
npm uninstall @alleyway/add-tradingview-alerts-tool -g
```

**Comment by akefallonitis** [comment]
Thanks it worked !

Anychance to do it headless ? if i change this line to true ? do i need to recompile it somehow ?

![image](https://user-images.githubusercontent.com/24274227/118243995-c013e700-b4a7-11eb-99a4-0e4d3153adf2.png)

**Comment by akefallonitis** [comment]
Actually tried it with headless true but i get this error:

![image](https://user-images.githubusercontent.com/24274227/118245504-922fa200-b4a9-11eb-92b2-1c6beecde83c.png)

**Comment by akefallonitis** [comment]
Actually with headless: true it does not like these 2 lines

        defaultViewport: null,
        args: headless ? null : [
            `--app=${config.tradingview.chartUrl}#signin`,
            // '--window-size=1440,670'
        ]

not sure why

**Comment by akefallonitis** [comment]
If i remove them it seems to run but no alerts show up on tradingview

**Comment by akefallonitis** [comment]
Figure it out its working with the right chart url without this line:

    args: headless ? null : [
        `--app=${config.tradingview.chartUrl}#signin`,
        // '--window-size=1440,670'
    ]

Again ty

**Comment by mlake** [comment]
👍
