### ISSUE TITLE
Error msg when adding the first alert

### ISSUE THREAD

**Issue by liyoungc** [alleyway/add-tradingview-alerts-tool#58]
The chart was shown properly on Chromium with an already login page. Here the error I encountered:

> lyc@LYCIMACWIN add-tradingview-alerts-tool % ./atat add-alerts config_qfl_usdt2.yml
> ℹ ATAT Version: 1.8.0 | Node Version: v16.0.0                         12:16:41
> ℹ Current log level: 3 (you can specify '--loglevel 5' for maximum debugging)
> ℹ Base delay: 1000 (you can specify '--delay 1000' (or env variable BASE_DELAY) to increase/decrease speed)
> ℹ Using config file:  config_qfl_usdt2.yml                            12:16:41
> ℹ Press Ctrl-C to stop this script                                    12:16:41
> ℹ Adding symbol: BINANCE:1INCHUSDT  ( 1INCH priced in USDT )          12:16:53
> 
>  ERROR  Cannot read property 'toString' of null                       12:16:58
> 
>   at addAlertsMain (node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:137:45)
>   at Command.<anonymous> (node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:67:13)
> 
> lyc@LYCIMACWIN add-tradingview-alerts-tool %

Do you have any clue? Thanks!

**Comment by mlake** [comment]
Update your tool, brah
