### ISSUE TITLE
Could this be adapted to handle other security types?

### ISSUE THREAD

**Issue by snoop244** [alleyway/add-tradingview-alerts-tool#63]
I've been looking for something like this for a while. I run multi-time-frame strategies across about 100 stocks. Updating TV alerts manually takes hours.

Could this be easily adapted to handle stocks or would I just be better starting from scratch to automate the browser? If adapting is possible, I could try digging into the code. I have zero experience with currency trading so the csv's you create aren't clear to me.

I would be fetching the stocks from an IBKR market scanner via their API. From a quick review of your YAML configuration, I assume the YAML would work for stocks - it's the csv part that might need to be very different.

**Comment by mlake** [comment]
Can try uploading a csv file of stock symbols at alertzmanager.io
