### ISSUE TITLE
Is it possible to also apply `strategies` as well rather than `alerts`?

### ISSUE THREAD

**Issue by avatar-lavventura** [alleyway/add-tradingview-alerts-tool#64]
I was wondering would it possible to also apply `strategies` as well rather than `alerts`?

When we choose a strategy its gui differs from the alert option like `Options` section is removed, would it cause a problem?

<img width="471" alt="image" src="https://user-images.githubusercontent.com/18537398/122378225-7454d180-cf6e-11eb-95e6-0fd6796a6f3f.png">

**Comment by mlake** [comment]
I believe can just omit the options value...haven't played with this much..please report back ;-)

**Comment by avatar-lavventura** [comment]
Will do! Hm there is no option for `Open-ended` as well, I will try to figure it out

**Comment by avatar-lavventura** [comment]
Also should we publish our own pine-script without applying it via `chartUrl`?

**Comment by avatar-lavventura** [comment]
I found a bug that could be helpful if its solved

```
› searching menu for strategy_name

 ERROR  Unable to partial match strategy_name in dropdown
```

But in tradingview original strategy name could be the long condiiton name as `strategy_name (7.5, 7.5, 6, 1, 12, 30, 2021, 2021, 10, 21, 70, 53, -70, -53, 0.5, 0.05, 0.05):` // some parameters are assigned in between `(` and `)`.  Can the search menu operation could be done if the menu items contains `strategy_name` name instead of the comparing he exact alert-name?

**Comment by avatar-lavventura** [comment]
The strategy is not applied when the program restarts it self so I have to manually do `add-to-chart`. But since the scripts runs pretty fast I am not able to do it. If it could sleep 10 seconds on the start-up that would be helpful for me to save the script into the chart and move on.

**Comment by gaurav1909** [comment]
which command did you run to add alerts?

**Comment by avatar-lavventura** [comment]
I did:

```
tradingview-alerts-home/node_modules/@alleyway/add-tradingview-alerts-tool/dist/add-alerts.js
./tradingview-alerts-home/atat --delay 1500 add-alerts
```

To be safe I keep `delay` value at 1500. It is pretty slow but it does not crush along the way. When its around `--500`, sometimes it is not able find the strategy name and program get crashed. I wish it is able to continue where it left of if crush occurs.

**Comment by gaurav1909** [comment]
would you help me. something is having problem

**Comment by avatar-lavventura** [comment]
If you have a running strategy I can for the setup but I am not that good in the nodejs side.

But its better to open a new issue and ask question pasting the error you are having. The developer could help you out.
