### ISSUE TITLE
When attempting to open the primary left dropdown, it actually opens the secondary

### ISSUE THREAD

**Issue by hermes3por3** [alleyway/add-tradingview-alerts-tool#79]
The fails with the error "Unable to partial match XXX in dropdown".

The most verbose log level says:
``› Searching potential dropdown xpath of primaryLeft
``› ...selector: //div[contains(@class, 'tv-alert-dialog__group-item--left ')]/span[@class='tv-control-select__wrap tv-dropdown-behavior ``tv-control-select--size_small']/span[@class='tv-control-select__control tv-dropdown-behavior__button']
``› Found dropdown! Clicking element of primaryLeft

But then it seems the secondary button is clicked instead. The button (checking from another browser) seems to have the right classes so that the xpath selector should work.

The funny thing is that yesterday it worked flawlessly.

![error](https://user-images.githubusercontent.com/990062/130284040-772a8f84-3ef7-4c7a-af60-302cf7ffbce8.jpg)

**Comment by mlake** [comment]
Not sure what could be wrong, but nobody else seems to be having this issue...might be related to your internet connection speed..closing this for now..
