### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by fekirsch** [alleyway/add-tradingview-alerts-tool#8]
Hi, first of all, thank you for developing this code!

I want to create alerts in bulk also for non crypto assets. So I exported the list of tickers from my trading view list in CSV, changed the input file in the config.yml to this new csv file, changed to my trading view chart URL also and the indicator parameters. I don't know if the error is related to me trying to use the script for these different tickers.

I have pasted the error below. Thanks!

Felipe@MacBook-Pro add-tradingview-alerts-tool % npm run add-alerts

> @alleyway/add-tradingview-alerts-tool@1.3.1 add-alerts /Users/Felipe/add-tradingview-alerts-tool
> tsc && node lib/add-tradingview-alerts.js

Using config file:  config.yml
Press Ctrl-C to stop this script
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.open (fs.js:443:10)
    at _openReadFs (internal/fs/streams.js:142:15)
    at new ReadStream (internal/fs/streams.js:119:5)
    at Object.createReadStream (fs.js:2003:10)
    at /Users/Felipe/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:20:12
    at new Promise (<anonymous>)
    at readFilePromise (/Users/Felipe/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:17:12)
    at /Users/Felipe/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:241:37
    at step (/Users/Felipe/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:33:23)
    at Object.next (/Users/Felipe/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:14:53) {
  code: 'ERR_INVALID_ARG_TYPE'
}
^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! @alleyway/add-tradingview-alerts-tool@1.3.1 add-alerts: `tsc && node lib/add-tradingview-alerts.js`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the @alleyway/add-tradingview-alerts-tool@1.3.1 add-alerts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Felipe/.npm/_logs/2021-02-06T16_09_40_080Z-debug.log
Felipe@MacBook-Pro add-tradingview-alerts-tool %

**Comment by mlake** [comment]
Hi Felipe - it seems like it's having an issue finding the configuration for the input csv...

The tabs in the configuration file matter, so maybe you've done something there?

```
files:
  input: your_csv_here.csv
  exclude: blacklist.csv
```

Feel free to post your config file and I could see if you've broken the structure..
-M

**Comment by fekirsch** [comment]
Hey, thanks Michael. The first is how my csv file is written and the second the config.yml file.


symbol | quote | base |  
-- | -- | -- | --
BMFBOVESPA:ABEV3 | AMB | BRL |  
BMFBOVESPA:AZUL4 | AZU | BRL |  
BMFBOVESPA:B3SA3 | B3S | BRL |  
BMFBOVESPA:BBAS3 | BBS | BRL |  
BMFBOVESPA:BBDC4 | BBD | BRL |  
BMFBOVESPA:BPAC11 | BTG | BRL |  
BMFBOVESPA:CIEL3 | CIE | BRL |  
BMFBOVESPA:COGN3 | COG | BRL |  
BMFBOVESPA:WIN1! | WIN | BRL |  



files:
  input: tradeinput.csv
  exclude:
tradingview:
  # The chart which has the indicator you'd like to use
  chartUrl: https://www.tradingview.com/chart/fRL0NuGQ/
  # (optional) set the chart interval before adding pairs, otherwise interval of last saved chart is used
  # examples: 1s | 30s | 1m | 15m | 1h | 1D | 1M
  interval: 1h
alert:
  condition:
    primaryLeft: TI Seq
    primaryRight: Alert Count
    secondary: Greater than
    tertiaryLeft: Value	
    tertiaryRight: 0
  option: Once Per Bar Close
  # alert name is optional - can override in csv if you add a "name" column. can use {{symbol|base|quote}}
  # name: "MI dev3 for {{base}} {{quote}}"
  # indentation matters! {{quote}} and {{base}} are swapped out for quote asset(eg. USDT) and the base (eg. BTC)
  message: >
    {
         "message_type": "bot",
         "bot_id": 999999,
         "email_token": "fffffff-fffff-fffff-ffff-ffffffffff",
         "delay_seconds": 0,
         "pair": "{{quote}}_{{base}}"
    }

**Comment by fekirsch** [comment]
Hey Michael, thanks, I just found out leaving exclude line empty caused the problem.
But now I this other problem. It worked with the finance .csv so it seems it is something with the tickers I am using. But don't see what is the problem.


Using config file:  config.yml
Press Ctrl-C to stop this script
TypeError: Cannot read property 'toLowerCase' of undefined
    at isBlacklisted (/Users/Felipe/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:245:28)
    at /Users/Felipe/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:261:17
    at step (/Users/Felipe/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:33:23)
    at Object.next (/Users/Felipe/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:14:53)
    at fulfilled (/Users/Felipe/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by fekirsch** [comment]
Hey, just found what was wrong. It was my csv file. I created it from scratch with the tickers. This time I just pasted the tickers lines into the binance.csv generated by the script and it worked.

**Comment by mlake** [comment]
😉
