### ISSUE TITLE
Is it possible to adjust settings between alerts?

### ISSUE THREAD

**Issue by cmartin81** [alleyway/add-tradingview-alerts-tool#84]
I want to adjust some configuration depending on which assets I'm going to create a alert for. Is this possible?
Ex
BTCUSDT => adjust a config number to 1 => create alert
ETHUSDT => adjust a config number to 2.5 => create alert
...
...

**Comment by mlake** [comment]
hmm…not currently, but I could perhaps add the possibility of tokenizing some values based on whatever you put in the csv…

For example if you added a column header that said “rsi_value” you’d be able to have a configuration like the following:

‘’’
  tertiaryLeft: “{{rsi_value}}”

‘’’

Is that workable?

**Comment by cmartin81** [comment]
I need to actually change values inside a indicator
<img width="785" alt="BTCUSDTPERP_45552_23_▲__1_54__Unnamed" src="https://user-images.githubusercontent.com/510413/132953828-9da37fbb-92a0-4698-8389-9ab37a53fb77.png">

<img width="380" alt="BTCUSDTPERP_45559_99_▲__1_56__Unnamed" src="https://user-images.githubusercontent.com/510413/132953841-fa21bcb0-8780-49d3-8159-d0628f1f2a32.png">

**Comment by cmartin81** [comment]
A perfect solution is that it can get a value from the CSV file.

**Comment by cmartin81** [comment]
I see from the code that you use shortcuts to open alerts windov. I did not find any shortcut for open indicator settings. But I guess you could find the cog by Xpath Queries

**Comment by mlake** [comment]
You can add indicators multiple times to the same chart, then create separate alert configurations

**Comment by cmartin81** [comment]
Can you please explain more? 
I have 12 different coins that have 12 different values inside the indicator.

**Comment by mlake** [comment]
So add the indicator 12 different times and adjust each value.

Then for the "primaryLeft" you use the entire indicator name (including the values)...

Have a look at the following screenshot

![image](https://user-images.githubusercontent.com/764071/132956953-90526055-e093-4037-8aa9-eaaa8354761d.png)

**Comment by cmartin81** [comment]
Ahh.. Thanks this will make it better :) I still need to go in and adjust values whenever I need adjust them (once a week). But having 12 indicators on 1 page shouldn't take long time. I then need to add the same values into the CSV file so it can pick the correct.I was hoping for a solution where I can put new values in CSV and inside the yaml file I can change the configuration for that indicator with input from csv file.

**Comment by cmartin81** [comment]
Here a update of what I did:
* added 12 indicators on same chart - OK
* change all indicators with different values - OK 
* added 2 new columns in csv file - OK
* added reg ex  inside  yaml file with variables from csv file - NOT ok
EX:
   ` primaryLeft: /^Foo\sAlgo.*Exits\s{{sensitivity}}.*None\s{{agility}}\sBottom.*`
  Looks like it does not changes out the variables from CSV file in to yaml file in primaryLeft

**Comment by mlake** [comment]
I was merely suggesting the possibility how that would work - in fact, I don't have that token-replacement functionality in there yet.

I can take a quick crack at making that work, and if I do, I'll let you try a beta before merging into the main codebase...

**Comment by cmartin81** [comment]
That would be great :)

**Comment by cmartin81** [comment]
If I should pick from the top shelf it would be ACE if you can go into a config and change this with properties from CSV file
Something like this:
<img width="1223" alt="CSV_file__and_BTCUSDTPERP_45988_80_▲__1_76__Unnamed" src="https://user-images.githubusercontent.com/510413/132981553-396f6309-54d5-49e8-8eb6-99bc4f2a3c2d.png">

**Comment by mlake** [comment]
Never hurts to ask for top-shelf features...Unfortunately I'm no longer a top-shelf or ace developer 😝  perhaps someday..

I believe I got the token-replacement from .csv working..you can try the beta by running the following in your tradingview-alerts-home directory:

```
tradingview-alerts-home % npm install @alleyway/add-tradingview-alerts-tool@beta
```

If it's working as you expected and I've not broken anything, let me know and I can release it for everyone else

**Comment by cmartin81** [comment]
Thank you. I'll test this later today! 
I might help you with my top-shelf features.... I know all the frameworks, but I'm not sure if I have the time.

**Comment by cmartin81** [comment]
Tried testing it now.
It does switch out the 1 variable
<img width="1225" alt="From_YML" src="https://user-images.githubusercontent.com/510413/132984797-6852af68-841e-488e-8e69-c5f1a2626c7a.png">
. But I have 2 variables inside the string, and that does not work.

**Comment by mlake** [comment]
the csv parser is by default pretty strict - I was confused at one point because I had a space next to the delimiting comma.
I just made a quick update to trim header names and give a little more warning output...

see if this fixes it..

```
tradingview-alerts-home % npm install @alleyway/add-tradingview-alerts-tool@1.9.0-beta.1
```

**Comment by cmartin81** [comment]
Nope, that did not work

**Comment by cmartin81** [comment]
Sorry my bad, it looks like it puts everything in regular expression now.

**Comment by cmartin81** [comment]
When creating a CSV file it created something like this
```
  symbol,base,quote,name
  BINANCE:BTCUSDT,BTC,USDT,
  BINANCE:ETHUSDT,ETH,USDT,
  ...
  ...
```
The name does not point to anything.  So this should be removed from CSV file

**Comment by cmartin81** [comment]
It should have made the matching now:
<img width="2458" alt="add-tradingview-alerts-tool_–_binance_lambo_fitted_pairs_csv_and_Regex_Tester_-_Javascript__PCRE__PHP" src="https://user-images.githubusercontent.com/510413/132987500-6e93812b-95e9-408e-a8f4-9a3aca7d8853.png">

**Comment by mlake** [comment]
almost there...

1) "name" column can be used if you want to give your alert a specific name

2) from your log file it looks as though you might be missing a final forward slash...
```yaml
primaryLeft: /^Lux #treated as string
```

```yaml
primaryLeft: /^Lux/ #treated as regex
```

**Comment by cmartin81** [comment]
Ahh.. Now it works :)
