### ISSUE TITLE
[feature_request] Running atat only to open browser that is signed in into our tradingview account

### ISSUE THREAD

**Issue by avatar-lavventura** [alleyway/add-tradingview-alerts-tool#86]
Its a more general question related to using [puppeteer google browser](https://github.com/puppeteer/puppeteer). When we are using premium freetrial version of tradinview, we have to keep using only the browser that is already connected into our account. If we use another browser, tradingview bans us. After alerts are added, it would be nice to able to open `puppeteer google browser` that `atat` uses and check status of the added alerts.

Can we add following function right before `if (accessDenied) {`, which will be called in case if we just want to open browser that is already sign-in into our username,password.  (`./atat --browser`). 

I believe this function just waits and we can use (analyze etc.) in the browser as we want.

[Waiting for user to enter input in Node.js](https://stackoverflow.com/a/50890409/2402577)
```
function askQuestion(query) {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });

    return new Promise(resolve => rl.question(query, ans => {
        rl.close();
        resolve(ans);
    }))
}
```

**Comment by mlake** [comment]
unfortunately not.

**Comment by avatar-lavventura** [comment]
@mlake Why its only few lines of code? Shouldn't be that difficult
