### ISSUE TITLE
atat- command not working.

### ISSUE THREAD

**Issue by jasurakk** [alleyway/add-tradingview-alerts-tool#87]
Hi!

And thank you for your great tool!

But, for some reason, I cannot fetch trading pairs with atat- command, I just always get this kind of an error:

PS C:\Users\jasurakk\add-tradingview-alerts-tool> ./atat fetch-pairs binance usdt
./atat : File C:\Users\jasurakk\add-tradingview-alerts-tool\atat.ps1 cannot be loaded because running scripts is dis
abled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=1
35170.
At line:1 char:1
+ ./atat fetch-pairs binance usdt
+ ~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

I checked the link where the error message is directing, but I just could not understand what should I do to fix this spesific issue... Any hints?

With best regards,

Jari

**Comment by mlake** [comment]
try a newer version

![image](https://user-images.githubusercontent.com/764071/152422895-b923db5e-4721-42db-ae2e-9d17dcea31da.png)
