### ISSUE TITLE
Remove Alert

### ISSUE THREAD

**Issue by binhna** [alleyway/add-tradingview-alerts-tool#9]
Hello, thanks for your great work

I want to ask if there is any script that I can automatically delete alerts besides adding them.

**Comment by mlake** [comment]
You can remove all alerts in tradingview

![image](https://user-images.githubusercontent.com/764071/107512885-bbd5e600-6ba7-11eb-853e-86039d377426.png)

Did you just want to remove just some alerts? How do you think that should work?

**Comment by binhna** [comment]
Thanks, that would work. Actually, there is an expiration time for alert now in tradingview, so after all the old alerts are expired, I want to automatically remove them and add them again with the new expiration time (using crontab or something like that).

So that would be great if the code has a script to remove them all instead of doing it manually.
![image](https://user-images.githubusercontent.com/18049173/107529619-a08dc980-6bed-11eb-8f97-ed08a56bde5f.png)

**Comment by aryabchenko** [comment]
Wow, awesome work!
@mlake can you add functionality to update/delete/disable alert ? So the script would not only add alerts, but keep configuration synced. So it's kind of extension from bulk-add script to control system. All modern control systems keep configuration and reality synchronized, so all you need is to update config and run the script. I use such systems daily in my work e.g. terraform, puppet, ansible, etc.

**Comment by Ajki-GH** [comment]
It would be great if we could also remove alerts by name with the script

**Comment by Ajki-GH** [comment]
> 
> 
> You can remove all alerts in tradingview
> 
> ![image](https://user-images.githubusercontent.com/764071/107512885-bbd5e600-6ba7-11eb-853e-86039d377426.png)
> 
> Did you just want to remove just some alerts? How do you think that should work?

Could you add a command that would delete all alerts, so we can run it before we run add alerts one. 
I made a bash script that is changing config and looping adding alerts for my coins on different time frame, I planned to run it in cron but atm before I add alerts I need to manually delete the old ones.

**Comment by mlake** [comment]
Try signing up as a beta tester at alertzmanager.io which has more comprehensive alert management
