### ISSUE TITLE
Version 1.9.1 Errors on base and quote 

### ISSUE THREAD

**Issue by Maacus** [alleyway/add-tradingview-alerts-tool#90]
Just updated and unfortunately get the following errors when creating alerts:

-  WARN  No key in .csv matches '{{base}}' - but might be using TradingView token-replacement                  
-  WARN  No key in .csv matches '{{quote}}' - but might be using TradingView token-replacement

When creating the alert, I reference {{base}}{{quote}} at the start, and this works fine.  However later in the alert, the same info cannot be resolved and produces the above error.  The alert is created, but incorrectly.  

It did work in all previous versions I've used.

Thanks

**Comment by mlake** [comment]
Thanks for reporting - could you perhaps post your alert configuration and .csv file for me to debug?

**Comment by Maacus** [comment]
CSV:
symbol,quote,base
BINANCE:ETHBTC,BTC,ETH
BINANCE:LTCBTC,BTC,LTC

Alert Message:
    {"key":"xxx","pair":"{{base}}{{quote}}","type":"entry","exchange":"binance","price":"{{close}}","stopLossPercentage":"{{plot_7}}","stopLossFollowsTakeProfit":true,"signalId":"{{base}}{{quote}}"}

Its the final {{base}}{{quote}} which errors, the rest is fine.

**Comment by mlake** [comment]
Thanks for providing that. I think I've got a fix working (among some other minor dependency updates)

From your ``tradingview-alerts-home`` directory, run the following:

```bash
npm install @alleyway/add-tradingview-alerts-tool@beta
```

Please report back if it's working okay and I will push a release.

**Comment by Maacus** [comment]
Yeah that's fixed it.

Thanks very much!

**Comment by mlake** [comment]
👍 
You can get back to the normal release with the following

From your ``tradingview-alerts-home`` directory, run the following:
```bash
npm install @alleyway/add-tradingview-alerts-tool@latest
```
