### ISSUE TITLE
Two messages in an alert

### ISSUE THREAD

**Issue by lordvalium** [alleyway/add-tradingview-alerts-tool#98]
Hi, 
i would like to trigger 2 bots on 2 email tokens. Can this be done in 1 message box within 1 alert?

  message: >
    {
        "message_type": "bot",
        "bot_id": 999999,
        "email_token": "fffffff-fffff-fffff-ffff-ffffffffff",
        "delay_seconds": 0,
        "pair": "{{quote}}_{{base}}"
    }

**Comment by mlake** [comment]
try this:

https://github.com/alleyway/add-tradingview-alerts-tool#send-a-single-alert-to-multiple-3commas-bots
